### ISSUE TITLE
timeMin and timMax parameters cause a Bad Request

### ISSUE THREAD

**Issue by whitemaker** [dart-lang/googleapis#14]
Issue:
Requests with timeMin or timeMax parameters fail with DetailedApiRequestError(status: 400, message: Bad Request).

Cause:
Because dart DateTime does not handle time zones, the function toIso8601String() does not append a z to the end of the string.  

Related Example:
In the the [Api explorer](https://developers.google.com/apis-explorer/#p/), entering a string generated by toIso8601String() will fail
FAILS:        2017-02-03T08:25:15.99878

adding z will work
SUCCESS:  2017-02-03T08:25:15.99878z

Code:
googleapis/calendar/v3.dart 
Line 1744:
>       _queryParams["timeMin"] = [(timeMin).toIso8601String()];

From the documentation
   * [timeMin] - Lower bound (inclusive) for an event's end time to filter by.
   * Optional. The default is not to filter by end time. Must be an RFC3339
   * timestamp with mandatory time zone offset, e.g., 2011-06-03T10:00:00-07:00,
   * 2011-06-03T10:00:00Z. Milliseconds may be provided but will be ignored.

Solution:
1. Have the function append z to the string.
2. Make the parameter a string instead of a datetime.
3. Let the servers handle requests without z appended.

**Comment by mkustermann** [comment]
The issue I think is that the date time that gets passed **needs to be in utc**:


```
% cat test.dart
void main() {
  print(new DateTime.now().toIso8601String());
  print(new DateTime.now().toUtc().toIso8601String());
}
% dart test.dart
2017-03-29T11:28:22.381692
2017-03-29T09:28:22.385097Z
```

The server requires UTC timestamps and I think it would be a mistake to make the generated code do the conversion automatically (it could easily happen that the date is utc but users accidentally used `new DateTime()` instead of `new DateTime.utc()`).

Hopefully using utc `DateTime` objects will fix your problem. Please reopen the issue if it does not.
