### ISSUE TITLE
Translate API not working correctly

### ISSUE THREAD

**Issue by rinukkusu** [dart-lang/googleapis#17]
For some reason, the Translate API is not generated correctly, I think.

In [translate/v2.dart#L590](https://github.com/dart-lang/googleapis/blob/3953f0d5fe4536a26fc4644a16b3e0fe9dfb4e5f/generated/googleapis/lib/translate/v2.dart#L590) it just checks for the existance of the `"translations"` key, while the `Map` actually has a toplevel `"data"` key.

Map object fed into the `fromJson` method:

```
{data: {translations: [{translatedText: Hello, detectedSourceLanguage: de}]}}
```

**Comment by rinukkusu** [comment]
Pinging @mkustermann - is there anything I can do to help you solve this?

**Comment by mkustermann** [comment]
Sorry for the slow response rate, have been quite busy. I'll take a look at it as soon as I've got some time!

**Comment by mkustermann** [comment]
So I've taken a look now and it seems that the translate api is using a special "feature" - namely the "dataWrapper" feature, where all request/response data should be wrapped. See [translate's discovery document](https://github.com/dart-lang/googleapis/blob/3953f0d5fe4536a26fc4644a16b3e0fe9dfb4e5f/discovery/googleapis/translate__v2.json#L22)

It appears that the translate API is the only api which uses this deprecated "dataWrapper" feature. It is described at [discovery-features](https://developers.google.com/discovery/v1/using#discovery-features):

*The dataWrapper feature indicates that all requests to and responses from the API are wrapped in a data JSON object. This is a feature of older Google APIs, but it is being deprecated moving forward. The following APIs support the dataWrapper feature: Moderator v1, and Translate v2.*


Our [discoveryapis_generator](https://github.com/dart-lang/discoveryapis_generator) simply ignores the `dataWrapper` feature and therefore doesn't wrap request/response objects. It should not be too hard to modify the generator to check for the `dataWrapper` feature and generate the code accordingly.

@rinukkusu We would be happy if you were interested in adding this feature to [discoveryapis_generator](https://github.com/dart-lang/discoveryapis_generator). Otherwise I can take care of it at some point.

**Comment by mkustermann** [comment]
@jakobr-google Would you be interested into looking at this?

I've already described what's the issue and how to fix it. It should be quite simple I think.

**Comment by jakobr-google** [comment]
I'll take a look at it.

**Comment by jakobr-google** [comment]
Here's a small sample that uses the Translate API (using an API key for authentication):
```dart
import 'dart:io';

import 'package:googleapis/translate/v2.dart';
import 'package:googleapis_auth/auth_io.dart';

main(List<String> args) async {
  final apiKey = new File('api.key').readAsStringSync();
  final client = await clientViaApiKey(apiKey);
  final translate = new TranslateApi(client);

  final q = ['Hello world!', 'I can translate stuff.', 'Vamos a la playa!'];

  final daResults = await translate.translations.list(q, 'da');
  for (final result in daResults.translations) {
    print('${result.translatedText} (${result.detectedSourceLanguage})');
  }

  final isRequest = new TranslateTextRequest()
    ..q = q
    ..target = 'is';
  final isResults = await translate.translations.translate(isRequest);
  for (final result in isResults.translations) {
    print('${result.translatedText} (${result.detectedSourceLanguage})');
  }

  await client.close();
}
```

Result of running this program (with a valid API key):
```
Hej Verden! (en)
Jeg kan oversætte ting. (en)
Lad os gå til stranden! (es)
Halló heimur! (en)
Ég get þýtt efni. (en)
Við skulum fara á ströndina! (es)
```

**Comment by rinukkusu** [comment]
Great, thanks a lot!! 👍

**Comment by justkawal** [comment]
> Here's a small sample that uses the Translate API (using an API key for authentication):
> 
> ```dart
> import 'dart:io';
> 
> import 'package:googleapis/translate/v2.dart';
> import 'package:googleapis_auth/auth_io.dart';
> 
> main(List<String> args) async {
>   final apiKey = new File('api.key').readAsStringSync();
>   final client = await clientViaApiKey(apiKey);
>   final translate = new TranslateApi(client);
> 
>   final q = ['Hello world!', 'I can translate stuff.', 'Vamos a la playa!'];
> 
>   final daResults = await translate.translations.list(q, 'da');
>   for (final result in daResults.translations) {
>     print('${result.translatedText} (${result.detectedSourceLanguage})');
>   }
> 
>   final isRequest = new TranslateTextRequest()
>     ..q = q
>     ..target = 'is';
>   final isResults = await translate.translations.translate(isRequest);
>   for (final result in isResults.translations) {
>     print('${result.translatedText} (${result.detectedSourceLanguage})');
>   }
> 
>   await client.close();
> }
> ```
> 
> Result of running this program (with a valid API key):
> 
> ```
> Hej Verden! (en)
> Jeg kan oversætte ting. (en)
> Lad os gå til stranden! (es)
> Halló heimur! (en)
> Ég get þýtt efni. (en)
> Við skulum fara á ströndina! (es)
> ```

This example does not works with latest version of Google Apis in dart

Any help is appreciated.
