### ISSUE TITLE
How to use custom search api

### ISSUE THREAD

**Issue by adityamv7** [dart-lang/googleapis#20]
I want to use custom search api for my flutter app for android   but there are no samples or tutorials  for using this please add some samples or tutorials for this

**Comment by adityamv7** [comment]
@jakobr-google  @mkustermann  can u help me ???

**Comment by jakobr-google** [comment]
Sure, how far did you get?

There's basic documentation for using the googleapis package at https://github.com/dart-lang/googleapis and https://www.dartdocs.org/documentation/googleapis/0.40.0/, and specifically for the custom search API at https://www.dartdocs.org/documentation/googleapis/0.40.0/googleapis.customsearch.v1/googleapis.customsearch.v1-library.html.

I don't know the specifics of custom search (https://developers.google.com/custom-search/json-api/v1/reference/), but it looks like you'll need to:

* Create a `CustomsearchApi` instance, passing in the necessary arguments (like what's shown in the README.md, just using `CustomsearchApi` instead of `StorageApi`).
* Get the `cse` instance from your `CustomsearchApi` instance.
* Call `cse.list(...)` and await the result.

And yes, more samples/tutorials and better documentation are definitely needed. It's on our list, but unfortunately so are other things with higher priority. If anyone wants to contribute samples/docs before we get to it, we'll happily take pull requests!

**Comment by adityamv7** [comment]
https://github.com/dart-lang/googleapis_examples/blob/master/customsearch_browser_apikey/web/index.dart
I tried modifying this old code but it did not work  
I will try this out and also do i need to import the http package for using this ? @jakobr-google

**Comment by mkustermann** [comment]
Generally speaking we cannot provide examples for every single auto-generated client API.

The hardest part is usually get authentication/authorization working. Afterwards it should be very straightforward: The generated client api libraries contain `*'Api` classes which take an `package:http/http.dart:Client` and then you can do API calls.

You can use [package:googleapis_auth](https://pub.dartlang.org/packages/googleapis) package for obtaining oauth2 credentials/clients for those APIs who use oauth2 or use [clientViaApiKey](https://www.dartdocs.org/documentation/googleapis_auth/0.2.3+6/googleapis_auth.auth_browser/clientViaApiKey.html) when using API keys.

For custom search in particular, you could take a look at the [source](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/frontend/search_service.dart) of the pub.dartlang.org api (which uses custom search atm).

**Comment by adityamv7** [comment]
Thanks for info but i wanted to ask whether google is going to shutdown custom search api ?
@jakobr-google @mkustermann 
because i think i read it somewhere

**Comment by mkustermann** [comment]
@adityamv7 Since we are working on the Dart team we have no insight into how long the custom search api will be supported. I can encourage you to look at the official custom search api documentation. 

There seems to be an XML api which is [deprecated](https://developers.google.com/custom-search/custom-search-api-list). Though, not sure about the json api.

Since this github repository is actually only used by us for generating client api libraries, I'll go ahead and close this issue.
