### ISSUE TITLE
[Dart2] Drive V3 File.fromJson type 'List<dynamic>' is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by neckaros** [dart-lang/googleapis#40]
Hello,

i'm having the following error when calling:
**files.list**
```
E/flutter ( 2708): type 'List<dynamic>' is not a subtype of type 'List<String>' where
E/flutter ( 2708):   List is from dart:core
E/flutter ( 2708):   List is from dart:core
E/flutter ( 2708):   String is from dart:core
E/flutter ( 2708):
E/flutter ( 2708): #0      new File.fromJson (package:googleapis/drive/v3.dart:4274:22)
E/flutter ( 2708): #1      new FileList.fromJson.<anonymous closure> (package:googleapis/drive/v3.dart:4546:37)
E/flutter ( 2708): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter ( 2708): #3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
E/flutter ( 2708): #4      new FileList.fromJson (package:googleapis/drive/v3.dart:4547:12)
E/flutter ( 2708): #5      FilesResourceApi.list.<anonymous closure> (package:googleapis/drive/v3.dart:1321:41)
E/flutter ( 2708): #6      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter ( 2708): #7      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
```

**Comment by eernstg** [comment]
I'm taking a look at this because it might be language related (I'm on the language team).

However, it looks like v3.dart 4274 should be `parents = _json["parents"].cast<String>();`. It is probably failing because it used to execute under Dart 1 semantics and is now running under Dart 2 semantics (which, among other things, means that `List<dynamic>` is no longer a subtype of `List<String>`).

This means that there is a need to update parts of `googleapis` to make it work correctly in Dart 2, but it doesn't raise any language issues per se. So I'll leave it to the folks who are maintaining this package to fix it, and just add a 'Bug' label. It seems to be generated code, so there might be a need for more complex changes, but that might be needed anyway in order to handle other locations in the code with a similar issue.

**Comment by zoechi** [comment]
Are you using the latest version `0.50.1` which was the update for Dart 2 #36
Might also be related to https://github.com/dart-lang/googleapis/issues/39#issuecomment-383024615

**Comment by jakobr-google** [comment]
I'll track all the Dart 2 issues in #35.
