### ISSUE TITLE
Firestore field expects String value for integerValue 

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/googleapis#81]
The following snippet will throw `int is not a subtype of String`:

```dart
// ...
final storeApi = FirestoreApi(authorizedClient);
final resp = await storeApi.projects.databases.documents.createDocument(
      Document.fromJson({
        'fields': {
          'intfield': {'integerValue': 55}
        }
      }),
      'projects/$PROJECT_ID/databases/(default)/documents/',
      COLLECTION_ID);
```

**Source of error:** https://github.com/dart-lang/googleapis/blob/ee696b1/generated/googleapis/lib/firestore/v1.dart#L5203

I can imagine a scenario where it'd make sense (eg. storing really large numbers) but most of the use-cases would consider this a bug. Is this intentional?

**Comment by jonasfj** [comment]
The [discovery document for firebase](https://firestore.googleapis.com/$discovery/rest?version=v1) referenced in [discovery APIs list](https://www.googleapis.com/discovery/v1/apis), says:
```
        "integerValue": {
          "description": "An integer value.",
          "format": "int64",
          "type": "string"
        },
```

Hence, I think this is intentional.

This package is automatically generated APIs. So it probably makes sense to use strings because that can represent large numbers. I would suggest finding/writing a wrapper around this package, to make a nicer API.

**Comment by jonasfj** [comment]
This package only provides APIs generated from discovery documents. Through these APIs many google services can be accessed, but the APIs can have rough edges.

A package like `package:gcloud` attempts to provide some nice wrappers for datastore and cloud storage. It would be nice to have the same for firestore, if someone haven't written it already :)
